apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgcopydb-app.fullname" . }}
  labels:
    {{- include "pgcopydb-app.labels" . | nindent 4 }}
    app: pgcopydb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pgcopydb-app.selectorLabels" . | nindent 4 }}
    app: pgcopydb
