apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgcopydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgcopydb
  template:
    metadata:
      labels:
        app: pgcopydb
    spec:
      containers:
      - name: pgcopydb
        image: advconreg.azurecr.io/pgcopydb-custom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: pgcopydb-storage
          mountPath: /app/pgcopydb_files
      volumes:
      - name: pgcopydb-storage
        persistentVolumeClaim:
          claimName: pgcopydb-pvc
      imagePullSecrets:
      - name: acr-secret