apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgcopydb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgcopydb-api
  template:
    metadata:
      labels:
        app: pgcopydb-api
    spec:
      containers:
      - name: pgcopydb-api
        image: advconreg.azurecr.io/pgcopydb-api:latest
        imagePullPolicy: Always   
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /docs
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-secret 