apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgcopydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgcopydb
  template:
    metadata:
      labels:
        app: pgcopydb
    spec:
      containers:
      - name: pgcopydb
        image: advconreg.azurecr.io/pgcopydb-custom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
