apiVersion: v2
name: pgcopydb-aks
description: A Helm chart for pgcopydb and pgcopydb-api services running on Azure Kubernetes Service

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"

keywords:
  - pgcopydb
  - kubernetes
  - azure
  - aks

maintainers:
  - name: Your Name
    email: your.email@example.com
