apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgcopydb-aks.name" . }}-pgcopydb
  labels:
    {{- include "pgcopydb-aks.labels" . | nindent 4 }}
    app: pgcopydb
spec:
  replicas: {{ .Values.pgcopydb.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgcopydb-aks.selectorLabels" . | nindent 6 }}
      app: pgcopydb
  template:
    metadata:
      labels:
        {{- include "pgcopydb-aks.selectorLabels" . | nindent 8 }}
        app: pgcopydb
    spec:
      containers:
      - name: pgcopydb
        image: "{{ .Values.pgcopydb.image.repository }}:{{ .Values.pgcopydb.image.tag }}"
        imagePullPolicy: {{ .Values.pgcopydb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.pgcopydb.service.targetPort }}
        resources:
          {{- toYaml .Values.pgcopydb.resources | nindent 12 }}
        volumeMounts:
        - name: pgcopydb-storage
          mountPath: /app/pgcopydb_files
      volumes:
      - name: pgcopydb-storage
        persistentVolumeClaim:
          claimName: {{ include "pgcopydb-aks.fullname" . }}-pvc
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}