apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pgcopydb-aks.fullname" . }}-pvc
  labels:
    {{- include "pgcopydb-aks.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | default "managed-premium" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}