apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgcopydb-aks.name" . }}-api
  labels:
    {{- include "pgcopydb-aks.labels" . | nindent 4 }}
    app: pgcopydb-api
spec:
  replicas: {{ .Values.pgcopydbApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgcopydb-aks.selectorLabels" . | nindent 6 }}
      app: pgcopydb-api
  template:
    metadata:
      labels:
        {{- include "pgcopydb-aks.selectorLabels" . | nindent 8 }}
        app: pgcopydb-api
    spec:
      containers:
      - name: pgcopydb-api
        image: "{{ .Values.pgcopydbApi.image.repository }}:{{ .Values.pgcopydbApi.image.tag }}"
        imagePullPolicy: {{ .Values.pgcopydbApi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.pgcopydbApi.service.targetPort }}
        resources:
          {{- toYaml .Values.pgcopydbApi.resources | nindent 12 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "{{ .Values.pgcopydbApi.service.targetPort }}"
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.pgcopydbApi.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: {{ .Values.pgcopydbApi.readinessProbe.periodSeconds }}
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.pgcopydbApi.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 6
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}